# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEQeLsvhAEY3zHNnx9EXyhouVIMUumNt
"""

#Website Traffic Analysis 3
visitors =[120, 250, 180, 300, 90, 210, 160]

highest_traffic = max(visitors)
lowest_traffic = min(visitors)


print("Daily Website Visitors counts for 7 days:", visitors)
print("Highest traffic Day:",highest_traffic)
print("Lowest traffic Day:", lowest_traffic)

#Customer Purchase Validation 4
purchase_amount=float(input("enter puchase amount:"))
if purchase_amount>0:
  print("valid")
else:
  print("invalid",)

# Inventory Stock Comparison 5
opening_stock=[200,156,55,399]
closing_stock=[399,58,77,999]
for i in range(len(opening_stock)):
  if closing_stock[i]>opening_stock[i]:
    print(f"product{i+1}: stock increased")
  elif closing_stock[i]<opening_stock[i]:
    print(f"product{i+1}: stock decreased")
  else:
    print(f"product{i+1}: stock remained same")

# Student Course Mapping 6
Student_Courses={
     "Asha":"Python",
     "Ravi":"Data Analytics",
     "Neha":"AI"
 }
print ("Student Names:")
for Student in Student_Courses.keys():
  print(Student)
print("\nEnrolled Courses:")
for Course in Student_Courses.values():
  print(Course)
student_name=input("Enter student Name:")
if student_name in Student_Courses:
  print(f"\n{student_name} is enrolled in {Student_Courses[student_name]}")
else:
  print(f"\n{student_name} is not enrolled in any courses")

