# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBtIKAzHf6QZb8WYNwOoyLYCBj4D19ot
"""

#Delivery Distance Category 7
delivery_distance=int(input(" delivery distance in km:"))
if delivery_distance<=5:
  print("Local")
elif delivery_distance>=6-20 and delivery_distance==20:
  print("Outstation")
else:
  print("City")

#Online Exam Score Analyzer 8
student_scores=[50,88.5,98,63.23]
total_score=sum(student_scores)
average_score=total_score/len(student_scores)
print("Total Score:",total_score)
print("Average Score:",average_score)
count_of_scores_above_average=0
for score in student_scores:
  if score >= average_score:
    count_of_scores_above_average+=1
print("Number of scores above average:", count_of_scores_above_average)

#product price lock system 9
fixed_product_price= (55,99,199,89,299)
print(fixed_product_price[0])
fixed_product_price[1]=54

#Feedback Count Dashboard 10
feedbacks={
    "Positive":45,
    "Neutral":18,
    "Negative":7,
}
total_feeddback=sum(feedbacks.values())
print("Total Feedbacks:",total_feeddback)
sachin=max(feedbacks)
print ("Highest Feedback Type:",sachin)