# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A50bBTo-o44Z9H7ylZqDgdffsPCrSoAK
"""

#Online Order Summery Generator
item_prices = [199, 1299, 299, 799, 198]
total_order_value = sum(item_prices)
average_price = total_order_value / len(item_prices)
print("Item Prices:", item_prices)
print("Total Order Value: ", total_order_value)
print("Average Item Price: ", average_price)

# Product Category Tracker
item_prices=[3,4,5,6,7]
t_order_v=sum(item_prices)
ave_order_v=t_order_v/len(item_prices)
print("item_prices:",item_prices)
print("t_order_v:",t_order_v)
print("ave_order_price:",ave_order_v)

#Website Traffic Analysis
from typing import ValuesView
products={
    "Laptop":"Electronics",
    "Chair":"Furniture",
    "Mobile":"Electronics"
}
for categories in products.keys():
    print("products name:",categories)
for categories in products.values():
    print("categories: ",categories)
print(len(products))

